<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="coverlet.collector" />
	  <PackageReference Include="CsCheck" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.17" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" />
	  <PackageReference Include="xunit" />
	  <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flowmetry.API\Flowmetry.API.csproj" />
  </ItemGroup>

</Project>
